### ISSUE TITLE
user-can-see-their-car

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/driving-game#2]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] create index.html file
- [x] create container for page and container for where car can dir
- [x] add car to html page
- [x] add car to html page
- [x] create stylings for html
- [x] style start position of the car to top left (start tests with absolute positioning - easier to adjust variables in position on absolute)
