### ISSUE TITLE
user-can-turn-their-car

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x]  add event listeners for all direction arrows in main.js
- [x]  create vars for the car and the container
- [x]  create a var for current direction that the rotater can check
- [x]  create function that changes direction of image
