### ISSUE TITLE
user-can-start-their-car

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/driving-game#4]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x]  add an if statement in the event liistener for space bar
- [x]  a function that starts the car by starting a timer interval for the car to move
- [x]  the function should quit and restart the timer so it is every single time the user pressed the space bar
